### ISSUE TITLE
新的报错

### ISSUE THREAD

**Issue by ilovemiku14** [PlexPt/chatgpt-java#1]
Cannot invoke "java.util.Map.containsKey(Object)" because "this.config" is null
resources里面已经配置号config。引入maven后测试代码没改。包如上错误

**Comment by ilovemiku14** [comment]
项目平行的文件夹也配置了。没用

**Comment by jevons9999** [comment]
要改根目录下的config.json

**Comment by PlexPt** [comment]
最新版已修复

**Comment by lmuiotctf** [comment]
运行了seesion好像不是读取config的，同时发送问题也没有回复
![image](https://user-images.githubusercontent.com/52068443/206353110-485152ae-fb4d-4d37-8c9d-5ee09bcd3ad8.png)

**Comment by PlexPt** [comment]
需要按2次回车

**Comment by PlexPt** [comment]
@lmuiotctf

**Comment by PlexPt** [comment]
![image](https://user-images.githubusercontent.com/15922823/206353660-47d99158-a664-4ade-b2f1-e2cc8ac68b74.png)

**Comment by lmuiotctf** [comment]
![image](https://user-images.githubusercontent.com/52068443/206367548-362f664c-532a-44c9-b021-0d4ac0c5d012.png)
I'm sorry, but I'm not able to understand the text you provided. It appears to be written in a language that I do not speak or understand. Can you please provide more information or context in a language that I can understand? I'll do my best to help if I have enough information.

**Comment by PlexPt** [comment]
> ![image](https://user-images.githubusercontent.com/52068443/206367548-362f664c-532a-44c9-b021-0d4ac0c5d012.png) I'm sorry, but I'm not able to understand the text you provided. It appears to be written in a language that I do not speak or understand. Can you please provide more information or context in a language that I can understand? I'll do my best to help if I have enough information.

字面意思

**Comment by lmuiotctf** [comment]
所以这是？？？哈哈哈哈

**Comment by lmuiotctf** [comment]
对不起，我无法理解您提供的文字。它似乎是用一种我不会说或听不懂的语言写的。您能否用我能理解的语言提供更多信息或上下文？如果我有足够的信息，我会尽力提供帮助。

**Comment by PlexPt** [comment]
你自己语句都不通顺

**Comment by lmuiotctf** [comment]
可以了 建议修改成为接口模式的 调取api来项目

**Comment by PlexPt** [comment]
https://github.com/TheoKanning/openai-java

**Comment by PlexPt** [comment]
这里有现成的api，但是跟网页不太一样

**Comment by lmuiotctf** [comment]
对  这个api和网页的有点不一样，所以就没有进行调式。
