### ISSUE TITLE
jdk8不支持编译此项目

### ISSUE THREAD

**Issue by LongerJzL** [PlexPt/chatgpt-java#100]
运行ConsoleChatGPT的main方法时，报：Exception in thread "main" java.lang.UnsupportedClassVersionError: ch/qos/logback/classic/spi/LogbackServiceProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 异常

**Comment by PlexPt** [comment]
https://github.com/PlexPt/chatgpt-online-springboot
