### ISSUE TITLE
简单示例出现报错 java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by mingzhennanqu** [PlexPt/chatgpt-java#101]
android集成为什么会报错啊，按照GitHub简单示例copy的
![图片](https://user-images.githubusercontent.com/109500975/230876246-e5d96aad-fe33-4370-a5ba-5d8b97d7cf32.png)
![图片](https://user-images.githubusercontent.com/109500975/230876272-53ac3bea-e7da-4d76-a9cd-c71c024a07b7.png)

**Comment by PlexPt** [comment]
android暂不适配

**Comment by ZakharchenkoWork** [comment]
I'll just leave it here. Integrating in Android is not a big problem. You will need to copy and change classes(files directely to your project) that use slf4j and delete those imports/usage.  Plus don't forget to make requests(init here is also a request) NOT from UI thread.
