### ISSUE TITLE
SseStreamListener返回值乱码

### ISSUE THREAD

**Issue by 263055** [PlexPt/chatgpt-java#106]
在Controller中写下了如下代码：
@GetMapping("/chat/sse")
    @CrossOrigin
    public SseEmitter sseEmitter(@RequestParam String prompt) {
        //国内需要代理 国外不需要
        Proxy proxy = Proxys.http("127.0.0.1", 7890);
        ChatGPTStream chatGPTStream = ChatGPTStream.builder()
                .timeout(600)
                .apiKey("t")
                .proxy(proxy)
                .apiHost("https://api.openai.com/")
                .build()
                .init();
        SseEmitter sseEmitter = new SseEmitter(-1L);
        com.plexpt.chatgpt.listener.SseStreamListener listener = new SseStreamListener(sseEmitter);
        Message message = Message.of(prompt);
        listener.setOnComplate(msg -> {
            System.out.println("OK");
            //回答完成，可以做一些事情
        });
        chatGPTStream.streamChatCompletion(Arrays.asList(message), listener);
        return sseEmitter;
    }
  
当参数是英文是，可以正常返回，效果如下：
data:Hello

data:!

data: How

data: may

data: I

data: assist

data: you

data: today

data:?
但是中文的时候会出现乱码，效果如下；
data:鎮�

data:濂�

data:锛�

**Comment by PlexPt** [comment]
控制台编码设置UTF8
