### ISSUE TITLE
向大佬请教个问题，你们是怎么突破ChatGPT对于tokens的限制且实现上下文功能的。

### ISSUE THREAD

**Issue by enguangzhang** [PlexPt/chatgpt-java#117]
我试用了https://chat.plexpt.com/，确实很流畅。所以就有以下疑问，麻烦大佬有时间帮忙解下疑。
1、据OpenAi官网接口信息来看，单次请求会有tokens的限制（ChatGPT-3.5是4k，ChatGPT-4分别是8k、32k）。若要实现上下文功能，就需要把历史消息带着发给ChatGPT，随着对话增加，每次请求的tokens也会越来越多，总会有超的时候。据我试用https://chat.plexpt.com/的感受，该网站的实现方式应该不是我上面说的那样吧。

**Comment by jaychoubaby** [comment]
同问，并且发现上下文对话能力很差，对比与node的那个服务，上下文对话能力差很多，是配置的问题还是api请求逻辑的问题呢？
参考：
https://github.com/Chanzhaoyu/chatgpt-web

![image](https://user-images.githubusercontent.com/26641387/235081026-b05fc52c-8d79-4f75-89db-98e0e335468a.png)
![image](https://user-images.githubusercontent.com/26641387/235081066-215528e7-f2c5-4896-a990-916779436caa.png)

**Comment by steADM** [comment]
> 同问，并且发现上下文对话能力很差，对比与node的那个服务，上下文对话能力差很多，是配置的问题还是api请求逻辑的问题呢？ 参考： https://github.com/Chanzhaoyu/chatgpt-web
> 
> ![image](https://user-images.githubusercontent.com/26641387/235081026-b05fc52c-8d79-4f75-89db-98e0e335468a.png) ![image](https://user-images.githubusercontent.com/26641387/235081066-215528e7-f2c5-4896-a990-916779436caa.png)

你这第一种明显是把前几个问题串起来又提问了一次，相当于最后是回答了“你好，李白是谁，望庐山瀑布是他写的吗”，所以ai才会这么回，第二个才是真正的有上下文。

**Comment by blueokanna** [comment]
> 
我不知道是不是可以使用这个getID去获得这个上文的内容，然后去写入到Assistance里面去
