### ISSUE TITLE
不能联系上下文对话

### ISSUE THREAD

**Issue by jaychoubaby** [PlexPt/chatgpt-java#120]
对比与node的那个服务，上下文对话能力差很多，是配置的问题还是api请求逻辑的问题呢？
参考：
https://github.com/Chanzhaoyu/chatgpt-web

![image](https://user-images.githubusercontent.com/26641387/235081026-b05fc52c-8d79-4f75-89db-98e0e335468a.png)
![image](https://user-images.githubusercontent.com/26641387/235081066-215528e7-f2c5-4896-a990-916779436caa.png)

**Comment by PlexPt** [comment]
https://github.com/PlexPt/chatgpt-online-springboot
