### ISSUE TITLE
onEvent好像从5月4号开始接收不到[Done]这条消息了

### ISSUE THREAD

**Issue by sekingme** [PlexPt/chatgpt-java#122]
之前一直可以的，但貌似azure返回的[Done]消息去掉了一个/n换行符，现在onEvent直接收不到这条消息；postman调用同样收不到。但命令行curl调用是可以收到的

**Comment by Pigeon-fancier** [comment]
> 

可以用fetch，在listener.setOnComplate(msg -> {
                    sseEmitter.complete();
                    //回答完成，可以做一些事情
                });里面记得关闭连接，不然fetch也不会自己关

**Comment by hebochang** [comment]
> > 
> 
> 可以用fetch，在listener.setOnComplate(msg -> { sseEmitter.complete(); //回答完成，可以做一些事情 });里面记得关闭连接，不然fetch也不会自己关

怎么关

**Comment by Pigeon-fancier** [comment]
> sseEmitter.complete()

我用fetch然后setOnComplate里面写sseEmitter.complete()，不然浏览器只能开两三个fetch就不能继续开了

**Comment by PlexPt** [comment]
https://github.com/PlexPt/chatgpt-online-springboot

**Comment by sekingme** [comment]
> https://github.com/PlexPt/chatgpt-online-springboot

这跟问题好像没联系？
