### ISSUE TITLE
[OkHttp https://api.openai.com/...] ERROR com.plexpt.chatgpt.listener.AbstractStreamListener - Stream connection error: {}

### ISSUE THREAD

**Issue by 15935856121** [PlexPt/chatgpt-java#125]
stream was reset: INTERNAL_ERROR
各位大佬这个问题是因为到达chatgpt的限制了嘛还是我这边的原因导致连接断了，我现在用的是gpt-4的接口，才生成了2000多个字的中文

**Comment by ljhssga** [comment]
请问gpt4接口申请大概要多久啊

**Comment by Pigeon-fancier** [comment]
大佬们，这个连接断了之类的异常要怎么捕获。。

**Comment by PlexPt** [comment]
https://github.com/PlexPt/chatgpt-online-springboot
