### ISSUE TITLE
同样是 offset 1, char a 这个报错

### ISSUE THREAD

**Issue by daozei6** [PlexPt/chatgpt-java#13]
下面是报错信息，使用的环境是线上
dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [/chatGPT] threw exception [Request processing failed; nested exception is com.alibaba.fastjso
n2.JSONException: illegal input， offset 1, char a] with root cause 
com.alibaba.fastjson2.JSONException: illegal input， offset 1, char a

**Comment by PlexPt** [comment]
token过期了吗

**Comment by DingGHui** [comment]
> token过期了吗

refreshSession方法中，请求[/api/](https://chat.openai.com/api/auth/session) 响应404
