### ISSUE TITLE
 Cloudflare 保护错误，http status: 403

### ISSUE THREAD

**Issue by jevons9999** [PlexPt/chatgpt-java#15]
"Request Url：https://chat.openai.com/api/auth/session Error，http status: 403，response body: <!DOCTYPE html>\n<html lang=\"en-US\">\n<head>\n    <title>Just a moment...</title>\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\n    <meta name=\"robots\" content=\"noindex,nofollow\">\n    <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n    <link href=\"/cdn-cgi/styles/challenges.css\" rel=\"stylesheet\">\n    \n\n</head>\n<body class=\"no-js\">\n    <div class=\"main-wrapper\" role=\"main\">\n    <div class=\"main-content\">\n        <h1 class=\"zone-name-title h1\">\n            <img class=\"heading-favicon\" src=\"/favicon.ico\"\n                 onerror=\"this.onerror=null;this.parentNode.removeChild(this)\">\n            chat.openai.com\n        </h1>\n        <h2 class=\"h2\" id=\"challenge-running\">\n            Checking if the site connection is secure\n        </h2>\n        <noscript>\n            <div id=\"challenge-error-title\">\n                <div class=\"h2\">\n                    <span class=\"icon-wrapper\">\n                        <div class=\"heading-icon warning-icon\"></div>\n                    </span>\n                    <span id=\"challenge-error-text\">\n                        Enable JavaScript and cookies to continue\n                    </span>\n                </div>\n            </div>\n        </noscript>\n        <div id=\"trk_jschal_js\" style=\"display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=7782e459dc16f649')\"></div>\n        <div id=\"challenge-body-text\" class=\"core-msg spacer\">\n            chat.openai.com needs to review the security of your connection before proceeding.\n        </div>\n        <form id=\"challenge-form\" action=\"/api/auth/session?User-Agent=Mozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_15_7)%20AppleWebKit/605.1.15%20(KHTML,%20like%20Gecko)%20Version/16.1%20Safari/605.1.15%20&amp;__cf_chl_f_tk=ieW6U6XkjndVLMnzRveMFcdlwE7pZYQv6iDaFfTdXrc-1670810694-0-gaNycGzNEWU\" method=\"POST\" enctype=\"application/x-www-form-urlencoded\">\n            <input type=\"hidden\" name=\"md\" value=\"5z04WRIi4WygZXRhBP2za3NQtmZPN1vznsi25cJ4rLM-1670810694-0-AYtbyF4hKRaA9hwZhMgeWdDKJKP2K9fCSxGqeuOgt88NKgFepiMlgsvJlry8bGb660JdeYWB_77gwhGDkHHwhr_peedFNKz-6MzDjhYpeCDAxKp0mISnScQYeHuH24aR0g7ihocOswVtKniwzQbRjwKpeSpEDrJxyDMBUi_hVDgw1nTFHbAVdHzntfclqRW62lab-fsm2EQTKufMmaD_byQapzxW3edc4mbNHkjoq0sRiKBlIeOUiBceQp_1NqHr0F532kHQU1-Ce6CRInZ2DB17roWGEP3-b7dsEUoHB87AeGsq-roVnDWgwRQOu21NgGeICs0RaBLege22pURzzg9T_Ej1OZ99KvjpUtrxmmHS9Hl-pF4MwiTt5h6VAGV1a-pMWK-Lcm5zk7B9wrL9iKN-ZFwH4Aj0a8M4QLyRNlxhvTco4FBRbHKBwMDuuW5ijGYIxxAkXwZHz7mjSg6Mo4jQyYISv3FnKUF6IUYFT4s2B967Y1mVo4hDHyKkOVGxoJLWdXiX--KMm9Nw15sNRSOJClRxDuyvGU--CJZbFy-B3nXaoTVetWuQSkFT3YdBtueu_nbS6gGY1yTkH26_XCuMFzB0tiekqcUpP7SWbzRHJzUZUEXYanG732KKoC0XrzM47qvSnEyt-ObIwRYjRUnFa-t_dNaBwujsaKQPm-SJGwHtGH0OAyPa97PPuw_2XRUgMswG1B2tMm4YcTW91Bz9tI9kZfJzMPWycvXfnShJDTkbW2uqJR7v5Dqx1yCeFH9jOE2m9L_6fn0gs9FR0s2qK63EQER2_yUYbpFMtUd-A_Q5NTqbB4-3yHUTJaQbFlY6H71thHbUy5cOr9g6Ic8kdIpNxLzdRHAJ4usrEVueX-gwfjHcKkXJuDdsRuRPzX_ix4tp56Iaz9s6yDeIqZ2s22zw4opL0UMl3kJwkFR7dOK0FYao-pWrjrZfaLHo__wdtSYAanbTpf9movWRg7zNOK5gz4lS8oJpxMlQWOb5qR53RFouksngJriJ1ybSP_6s3YpTRvovJxZROjnFGDoK3VkRspkNa8s8WkVKD4uH8Gu_A0i-UbxuqPG6UMB2hqiP2dX6XwL9nDnLuGRQB2A\">\n            <input type=\"hidden\" name=\"r\" value=\"o5r_H9Ri0w1EvVsfNdOUf37xKsr8.p22pCrbWji6GEM-1670810694-0-AT1ddB8ArWHTyfbUfC6W4u6hiYFHtKRQvNpl2mpWmX5G7uW3shDzDzJ0hBVpe+lPeevJMhKr0TMb3rfuQsGPv75POI5gKWgYT7UKczlJdzMCousYkOU/0szqGJ6Xx77ifV6u6qdln9pzZvOAUCUzOFGjvTD1DULPL+MMlib8FxfQOUbjRfWRUjXt5n2mPeRDKjNF0iV624SdhQ+qd03ZkQIJLRmYqogu4BILsvCG+/nWOi8wL+h2h2NRh6rh2ST05jSOufDntJVF/UxW9w5iUpx7AmdWpyZyqeGhFa+28Qrpbxr1Ftt6DO7F7fcW/wjTWxzbrH4t8VfD+m9551WUGrwnqr7q7wmIDroYNfigDj958Eq6oUhQvV5KRkCskGC0yQwO6tVG791Hr9iEny9MVDAx/1hTviEqRmiFyfPnZfPhs0NULqHli5gTdiy+jgM4QCBU9JZtXdTaWjg8n7VNpX3AtS6Ty4O3wW6rk3W76wqqsQTZAV8jl57rFcw/8Ro2zacMm/aVqiDl/AxXRPDLGvWoyLsDbwhPeK89ZPyvfFZ3PoTQ5453gaM5MzSWGkkps5RduH2KHm2pA7SEmMn0QV3ZSXM4l/oQWwvoE2GU+CQeXRBIExEI5ME3+zuCJy29B1QHDip55yKdEZGUGrzTVwZ28FEze4zRHg4S4i0XhzFZ5TUHb3V8RwgSH65B3BbG6mQ/Yv58Fm31VTxTZ+u3J1WWbxGFHH53TNL4LA1CY0jLSn7WwEPv8a8TND9AY1+WTPj/65AAwDDux+rYScXr6odiXzrmudtK5VGY+1ydpCv/+YdReZ4+iWyTTfB3EnQsCTad9Tq30UAtQmPst1WY9y4h6XqswEZjFhy6VehIgEF5P1kUJIUGWdi+NK5BOayBBAY62Q9fijj3aTbYeV79Z9BUYOdZpvyj4JF9852lUprJx5fKl9ySk20BXNo/XjPDjox4rNGkacle2qSL/+MUYyDUhEjKE3hpYeBrr1vRXIQQH3lWvykI0wvO4ma+KESDnikDQlBDRCLtAo5Cmw6zY++m9DUyyP2XSqlZ3NZoTeK7IIjSYCUQPNWhQ2X1aE2zmHQMxErx5zl4Ii5fH1KPLROG8nrzQcPANXXDySfN4SpB0In7SdlfcGvGlLQDAtCqVun/jwYK/Cc0c+773fKcb9wc5QPFPv2Shj/SeOHhcV0avGnfufXS762Ogq/+iOhUrfz7PY91lL91hASqxnUC4VszC/6Em4IiF/pEQ4DSGCbrOqhxhiBIbkKF62JqHIpxQHfK5Vbvc/MANDYZz444vtdU/MoRm3M17jo6fdzbkHlHwP4DwgCBFr732FFaBB3u3DeZ9wO7eM22PaZMHT7+mYdNogJrxDe671Gc8BfvZOrMqBtdJkrTeIS0IFOIF8OwbxgE4WU1z5Znp0S35a+DyLHi80tuisI+zsohNW5kSbXG4b1ayhwg2homvFbbyU59GDo74gFtDFjbPsD2+w5AHlEqbIYg8Bztw8x4k6HD39woZiwYN3x1mS3sQtQlr9+17TMLkBcjgXMff3TdLJ6rbs1niuYaf0DCxJYPnaVdC7HrJTeZmd4c7t/khcFjCTQ1BvEtZopRWLtOqY0JNfmv2Fw0ik3u3dKs51uWDDayNMsS9TTGqKga6T06f1bU9/tDUTQI/DOG1bKVukFjTHLFI0JEP8a3EGtBM1JY76ghKIkJKWe7h1wC62/MwdKdUuyWhBzQLlKUZLISQ/QYot2Q/8z4tqgExoCMxCOB+4dkyi3hD2eEiq3iYDi7NjgvwxxskAQlMYC7wlopXr4UcuNOgY+tVWad9u2f5QDxhmJO65lflx7D+FvUWLEmo37IvCCsLzQGUpm8VWmu3ZYh/O89BscrDWoo7ubgMdYlZ76SMks2fb0GG/VchdTmILnZ9h1oh23pQwCUZivcJm29GxclLVTpyZPojO709PH7a10P0oy+JxU+j4fUYtGfp821At9XKQP0U2mTXojYFESjpvjHa44kR9Hn3vJcBL7bhISWQ5zHS3F0tOYNV5bbQvMvmyDmXK8tm1kYDF9hhIc54WgIl6xE2+AilPjO5JSdy4eiBI1+hC+xm+OqIjljngRqctI4EN0XR83fZUzx+7R418wJ5/7AvsFxkFLzAdovKVRuIZcModMC6P2alPuIm7t9YC9Y2ydRIvqppX5eWUNXxEmfxW41NrSQTLatorWQ78ycEotVRpRSU82TVDYOWOu+asHw795Nl3ZtkaFsIyPlwA1TBSFwkhWa8Kl48nlcKMoXxkN5KO3XxnTYHfZfjia/F3xqfwLGNUpVLfpgnjLa7DU5P5jSE/ce52ms9eN1gqAMZ0YmaqEGmr5n1s+mK79OJK4dLLpwbweOXlpPDJKXOuRuRGEJQcK/xOjIoOT2cPjcQQlpJEiGFRBExStI5Yd2eP2drmPacxBgrLh3L1b2Tzsrq9++PUb+2qXXvW+WDxwD4/KPcNEd6FGN/zLQ6G3K2+SMBCbUuyQ46BKybyDg/AjTuvu5rbETVgsZojcuNsklp1pfKT5f0aoNutaelzrfCVCBVa43VF9pZG5eJ+VPStioLNbZ9VrXWVjTYOcxHISgy25UMQt+3sl/t3VbtR1z3qQcsePSXP1vLGn7JIDUIhbgHvnfRISQJhXgTS4cEfb+LseTDQyAcub/7An/Zecc5aceeM4zPzfiGCyy6LNA71m4yK1dsqbiFhxgVODeiZJghIv6QsDx5gUrEinnQU4O9yUBUSnaRrbK+QU1J/hyUeuxnUgoca4MvtyAoqkbp1LTl3HMXdt6Itc3dCuRyFSVKenVGJJz6UNF9skGhxsstpWXaOWLz2kap4r5Gq1+Z92U4odYJqmgx0ZvNlJ+rLD8OsYQawAoDmE2Co3CBaXwrczP8dYg/AUzgkrGKiQmnztPE+VbG3PaF0FEawOqObAZN0r16Z3eHXmU7wHsNY7t4SKEfLXwSznj3mrjAC5bDuyZ66mvNi9nsEcC+LTbwxodh5jT+ODKJVOd4nDX0H/rQnUILjLZy2E5TszYJ6g5sPONTe2//Uy1vlrzz3sJuw8G18n0Qr78KIfBUIMsnbDEQ+Lz1CgPBQ3N7pCSbPuodmhjFxXxxxhyIkVCczD/zO3xYBFJN8qit9ExOhw8jpsXZ7YVRnkHriuxBtAYyPuik3HOHJ27CKUbRuskuDjFKREN+/epvJSiwMUbS+mpRIq93SI1FuZrQLrx6wVyF3P5DrClBf3XdYJhI1CtIW2T3TewR+Zt2yCll3vYTAkPeHuAunKNdEmMrLvvPjBw91hcfysBsnHXxNBePXmcoNdJGPx2kMfpJP/wkvb4/+t+KaK0tN8m1JdEEHgdpMWxNsuKXRM0ivfaUMQ9g2A4gM+7q3S8vjCjLs20sHFv8pljejTJSkJEs2DvhM2RbN6mNFobaqPkrWhqzW4G8OAcdhYGHeSu/fARdBU9oz4DAqlXPwUSw1kTRPG6ooW4Bt6Ix09XTt6vjhuoxnaX958gjI6mQ4i5ky6Ryb8zY1+8O9Xh9uE+Qmpw1Pab2hel9f669dsEqSznUSB88Ct6WLNxEbdyqKXqqYQmn1gSrD+W/sDX+mhNG7yxjCRKw18aDZt+VRWt+rAOUWJPRFOyJv4FpTpFJSvZ33AWmcutfTo0P3eLj9DLpi1olkrMOXWlMQ4rg5W7NOwr4rY3F485pk7j77FzVeoa5JrqZG6OrF1GB362N/NRWoAbWnk85bkWmchPFG17vRFTCdVSX+5h1o3WRSrPxvmM7juWQkWVR6qXvZzLTjzjetiKt6rd1nETG2Eqbx9Vtj9CioZ3I5UWCNepf8U2mdmGiWICTogvUrk2Q/Z364zjr+WjrY7lsMX/b5XZMzovqOgET1Ndxe6W0G9EHfjleiRHfInXDtehDD21aJj910J2mzfgDSEmHP/XNhfWPqqwDcAymOBg5fd2sE4SuUIss96pBZy3O9CbPqNgX8Ug2+C+YI+h9rsz4s75/lRfNQ0yEO7TPGpR7PFTOoznh2OO2nW4A089qNl3ygmqklmhBkXvLkQbshl7Ev8hPXZNNdoNi2hwd5AvPy+Ud89p1AR2PZ0F65ZKEtlooYNpSn2PdsHCSvKUQIVyOKW4ERCnbqPBby0JxwODXLeprKms2d7FjS45T95/g0021aD4oLiJZmCETHt0WtwhB+QFG4ex/Di6mZZ1yolQ0cz1JSQWKesJ+2B9l9tiY1VeoXkDAVBYrMm4h71a5l/osmhUwt/OENSGfV/8BtkVJHYGND1GwrEHqB2GY29PUn2BKnvyxIiiUwv8tlDR8DTYzV4t6usGC74Kt+Nne48JfJ4ldjhTuu+i075rP1/mpZzCceeeqRGO73GUCeEA59aaAPQTOdhRE90u5DGQGz1c\">\n        </form>\n    </div>\n</div>\n<script>\n    (function(){\n        window._cf_chl_opt={\n            cvId: '2',\n            cType: 'managed',\n            cNounce: '69904',\n            cRay: '7782e459dc16f649',\n            cHash: '93c415a1ab5b12b',\n            cUPMDTk: \"\\/api\\/auth\\/session?User-Agent=Mozilla\\/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_15_7)%20AppleWebKit\\/605.1.15%20(KHTML,%20like%20Gecko)%20Version\\/16.1%20Safari\\/605.1.15%20&__cf_chl_tk=ieW6U6XkjndVLMnzRveMFcdlwE7pZYQv6iDaFfTdXrc-1670810694-0-gaNycGzNEWU\",\n            cFPWv: 'b',\n            cTTimeMs: '1000',\n            cTplV: 4,\n            cTplB: 'cf',\n            cRq: {\n                ru: 'aHR0cHM6Ly9jaGF0Lm9wZW5haS5jb20vY2hhdC9mcm9udGVuZC8vYXBpL2F1dGgvc2Vzc2lvbj9Vc2VyLUFnZW50PU1vemlsbGEvNS4wJTIwKE1hY2ludG9zaDslMjBJbnRlbCUyME1hYyUyME9TJTIwWCUyMDEwXzE1XzcpJTIwQXBwbGVXZWJLaXQvNjA1LjEuMTUlMjAoS0hUTUwsJTIwbGlrZSUyMEdlY2tvKSUyMFZlcnNpb24vMTYuMSUyMFNhZmFyaS82MDUuMS4xNSUyMA==',\n                ra: 'TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzc1LjAuMzc3MC4xNDIgU2FmYXJpLzUzNy4zNiBIdXRvb2w=',\n                rm: 'R0VU',\n                d: 'TmRGnyPlw4RMf1piCTbE97xcA8Tj98PZeoSASyYrwBc86gmkojwDkVEE7Ac1oJLwJj83ZLP1sQPuhRoobALJAyzBKFobzMq1lVs9fL5gn/d+fyyPiCJxxSwv+J08f8GAMILK6dWCeE8zEvXBPtSiZcI8iDLCBJvms9hSXyTYNiy+Ha10/EPkq3zR+6SJtOW3LTI4RD2vz/FS4ahoBIb6OX81YpsU7pDeflXplQkFZ6X1Dp/ZOSq8Zwnmn5vuzz5nNoObTGmJizWA9iGCgjVY9quJnD2Q9FLoMgPhH1FjvRyMdTwGbasY+T7W751wXQoBEycA2v4x1Wc1fjm9ybVrah6buw+RvQPNLU6PRyZRGM8MYyTAvLKjaR545N/VNe74VGOvZ21Qjhm91J5b4DJvlFuWsi3z2E3qLYvsUelJ+Qz+LvcczpBhlpesJzYyQS3MptvOBNDQHGvULxwSCF2kfBPt9LdMEzDV814LDnKF2FqYnC7+IPnYpobv0SmzKy6llEKlresrjyiWrRzpLnRP4dh2xKY7pldXWfnLioxc3MHJqxm/MjWm8roU2cF0edq4xQRz+7nV0o+3ii0sfegrbmq261F/hKoMzF1ngWo7m/kICOq9sw1Uj03sVevgD++Maboi8Diq/O0lH5RD1D5xKA==',\n                t: 'MTY3MDgxMDY5NC42OTcwMDA=',\n                m: 'OSkgGI4O+fvUj5NuuWoQXmMP3NQVCt674FCwpVQU13k=',\n                i1: 'SFCNKzBY5dQ0nf1TZ9eu8A==',\n                i2: 'uPNGaTu9qc3uYxUX0JMBYQ==',\n                zh: 'iuyN59AGNgeBFFEOPj72EN+xtBfXXvoCyd1dJnIVFAc=',\n                uh: 'py8TuFwMuZahQkeF3ttRvXcms553YCnt/83EpkJExhU=',\n                hh: 'foaWmAUHGGlVCZaNUJIHhxzxFNzSPNnVe6rJjiQw728=',\n            }\n        };\n        var trkjs = document.createElement('img');\n        trkjs.setAttribute('src', '/cdn-cgi/images/trace/managed/js/transparent.gif?ray=7782e459dc16f649');\n        trkjs.setAttribute('style', 'display: none');\n        document.body.appendChild(trkjs);\n        var cpo = document.createElement('script');\n        cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/managed/v1?ray=7782e459dc16f649';\n        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;\n        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, -window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;\n        if (window.history && window.history.replaceState) {\n            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;\n            history.replaceState(null, null, \"\\/api\\/auth\\/session?User-Agent=Mozilla\\/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_15_7)%20AppleWebKit\\/605.1.15%20(KHTML,%20like%20Gecko)%20Version\\/16.1%20Safari\\/605.1.15%20&__cf_chl_rt_tk=ieW6U6XkjndVLMnzRveMFcdlwE7pZYQv6iDaFfTdXrc-1670810694-0-gaNycGzNEWU\" + window._cf_chl_opt.cOgUHash);\n            cpo.onload = function() {\n                history.replaceState(null, null, ogU);\n            };\n        }\n        document.getElementsByTagName('head')[0].appendChild(cpo);\n    }());\n</script>\n\n\n    <div class=\"footer\" role=\"contentinfo\">\n        <div class=\"footer-inner\">\n            <div class=\"clearfix diagnostic-wrapper\">\n                <div class=\"ray-id\">Ray ID: <code>7782e459dc16f649</code></div>\n            </div>\n            <div class=\"text-center\">Performance &amp; security by <a rel=\"noopener noreferrer\" href=\"https://www.cloudflare.com?utm_source=challenge&utm_campaign=m\" target=\"_blank\">Cloudflare</a></div>\n        </div>\n    </div>\n</body>\n</html>\n"

**Comment by PlexPt** [comment]
今天，OpenAI 添加了额外的 Cloudflare 保护，这使得访问非官方 API 变得更加困难。 这会影响目前所有的 ChatGPT API 包装器，包括 Python 包装器。 请参阅[此问题](https://github.com/transitive-bullshit/chatgpt-api/issues/96)。

作为临时解决方法，请确保您使用的是此软件包的最新版本并且 Node.js >= 18：

1. 登录 https://chat.openai.com/chat 并复制一个新的会话令牌（与下面的说明相同）。
2. 复制 cf_clearance cookie 的值并将其存储在 CLEARANCE_TOKEN 环境变量以及您的 SESSION_TOKEN 中。
3. 从浏览器网络选项卡中的任何请求中复制浏览器的用户代理标头。
4. 创建 API 包装器时同时使用令牌和用户代理

**Comment by PlexPt** [comment]
#25
