### ISSUE TITLE
更新4.1.1版本后，非function call的请求过去openai 报错

### ISSUE THREAD

**Issue by popppo321** [PlexPt/chatgpt-java#150]
{
  "error": {
    "message": "Invalid value for 'function_call': 'function_call' is only allowed when 'functions' are specified.",
    "type": "invalid_request_error",
    "param": "function_call",
    "code": null
  }
}

**Comment by popppo321** [comment]
普通请求不应传递function_call参数

**Comment by Emmeet** [comment]
> 

没传递也报错

**Comment by PlexPt** [comment]
4.1.2 一 修复
