### ISSUE TITLE
SseEmitter配合流式使用的问题

### ISSUE THREAD

**Issue by ysf-wang** [PlexPt/chatgpt-java#160]
当我让它使用英文回复时，前端拿到的eventSource中每个data不含空格和换行符吗？如果拼接在一起的话就变成一大串连续的英文字母了。我看示例中的中文格式显示挺正常的，这个需要怎么处理一下吗？

**Comment by PlexPt** [comment]
你可能在找这个，参考Demo https://github.com/PlexPt/chatgpt-online-springboot

**Comment by ysf-wang** [comment]
> 你可能在找这个，参考Demo https://github.com/PlexPt/chatgpt-online-springboot

倒不是这个问题，我不知道为什么，在AbstractStreamListener里看到的msg是带空格的，前端js里eventSource.onmessage用event.data获取到的就是没有空格和换行符，暂时先用个对象套了转json再用SseEmitter.send解决了

**Comment by PlexPt** [comment]
你看这个demo里面有前端代码



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月6日(周四) 晚上7:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [PlexPt/chatgpt-java] SseEmitter配合流式使用的问题 (Issue #160)




  
你可能在找这个，参考Demo https://github.com/PlexPt/chatgpt-online-springboot
  
倒不是这个问题，我不知道为什么，在�AbstractStreamListener里看到的msg是带空格的，前端js里eventSource.onmessage用event.data获取到的就是没有空格和换行符，暂时先用个对象套了转json再用SseEmitter.send解决了

**Comment by ysf-wang** [comment]
> 你看这个demo里面有前端代码
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年7月6日(周四) 晚上7:28 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [PlexPt/chatgpt-java] SseEmitter配合流式使用的问题 (Issue #160) 你可能在找这个，参考Demo https://github.com/PlexPt/chatgpt-online-springboot 倒不是这个问题，我不知道为什么，在�AbstractStreamListener里看到的msg是带空格的，前端js里eventSource.onmessage用event.data获取到的就是没有空格和换行符，暂时先用个对象套了转json再用SseEmitter.send解决了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

感谢大佬，问题解决了。对比了一下demo和sdk的代码，sdk中AbstractStreamListener的中SseEmitter最后send出去的是ChatGpt Message对象的content字段，demo中是直接发送的Message对象，所以demo前端用了JSON.parse能正确拿到内容，但是sdk直接发送content不知为何前端拿到的少了空格和换行符（这个问题我最后也没找到，怀疑是编码，springboot Conveter的问题），最后解决方式一样是发送json到前端解析能正确拿到空格和换行符。
代码对比，AbstractStreamListener：
`public void onEvent(EventSource eventSource, String id, String type, String data) {
        if (data.equals("[DONE]")) {
            onComplate.accept(lastMessage);
            return;
        }

        ChatCompletionResponse response = JSON.parseObject(data, ChatCompletionResponse.class);
        // 读取Json
        List<ChatChoice> choices = response.getChoices();
        if (choices == null || choices.isEmpty()) {
            return;
        }
        Message delta = choices.get(0).getDelta();
        String text = delta.getContent();

        if (text != null) {
            lastMessage += text;

            onMsg(text);

        }

    }`
    demo中的GPTEventSourceListener :
    ` @SneakyThrows
    @Override
    public void onEvent(EventSource eventSource, String id, String type, String data) {
        log.info("回答中：{}", data);
        if (data.equals("[DONE]")) {
            log.info("回答完成：" + last);
            onComplate.accept(last);
            SseHelper.complete(sseEmitter);
            return;
        }

        ChatCompletionResponse completionResponse = JSON.parseObject(data,
                ChatCompletionResponse.class); // 读取Json
        Message delta = completionResponse.getChoices().get(0).getDelta();
        String text = delta.getContent();
        if (text != null) {
            last += text;

            sseEmitter.send(delta);
        }
    }`
    再次拜谢大佬！
