### ISSUE TITLE
WX小程序怎么接收流式请求？

### ISSUE THREAD

**Issue by AnotherJ1** [PlexPt/chatgpt-java#167]
我看实例里面的返回值是SseEmitter ，微信调用的时候必须要等服务端全部响应结束才能显示，这样导致中间会等很久。
微信小程序怎么一边接收一边显示？

**Comment by AnotherJ1** [comment]
已解决，微信开放社区找的
https://developers.weixin.qq.com/community/develop/doc/0002aeb6b38cc816e7fdc2ef95b800?highLine=Sse%2520Emitter
![image](https://github.com/PlexPt/chatgpt-java/assets/20277331/b8e12323-3e15-4482-9c73-80f0bc006500)

**Comment by PlexPt** [comment]
微信小程序现在支持SSE

**Comment by SoftwareEngineerPalace** [comment]
> https://developers.weixin.qq.com/community/develop/doc/0002aeb6b38cc816e7fdc2ef95b800?highLine=Sse%2520Emitter

确定吗？

怎么用？

**Comment by SoftwareEngineerPalace** [comment]
> 微信小程序现在支持SSE

确定吗，怎么用
