### ISSUE TITLE
我在前端收到的数据流没有收到换行符，但是debug的是否发现gpt确实是返回了换行的

### ISSUE THREAD

**Issue by Jeffrey2971** [PlexPt/chatgpt-java#207]
`
const eventSource = new EventSource('http://127.0.0.1/chat/sse?prompt=' + this.q);

                    
     eventSource.addEventListener('message', event => {

     console.log(event.data)
                    
                    });
`  

    @GetMapping("/chat/sse")
    @CrossOrigin
    public SseEmitter sseEmitter(String prompt) {
       //国内需要代理 国外不需要
       Proxy proxy = Proxys.http("127.0.0.1", 1080);

       ChatGPTStream chatGPTStream = ChatGPTStream.builder()
                .timeout(600)
                .apiKey("")
                .proxy(proxy)
                .apiHost("https://api.openai.com/")
                .build()
                .init();
        
        SseEmitter sseEmitter = new SseEmitter(-1L);

        SseStreamListener listener = new SseStreamListener(sseEmitter);
        Message message = Message.of(prompt);

        listener.setOnComplate(msg -> {
            //回答完成，可以做一些事情
        });
        chatGPTStream.streamChatCompletion(Arrays.asList(message), listener);

        return sseEmitter;
    }

**Comment by PlexPt** [comment]
有类似问题，翻一下前面的issue
