### ISSUE TITLE
ChatGPTStream是否支持gpt4?

### ISSUE THREAD

**Issue by wanglg007** [PlexPt/chatgpt-java#217]
![image](https://github.com/PlexPt/chatgpt-java/assets/40556406/8932b58d-2a91-4ede-aeea-60c3e2d20901)
 ChatGPTStream chatGPTStream = ChatGPTStream.builder()
                .timeout(3600)
                .model(ChatCompletion.Model.GPT4Turbo.getName())
                .apiKey(APIKEY)

**Comment by PlexPt** [comment]
支持
