### ISSUE TITLE
java.lang.ExceptionInInitializerError 报错

### ISSUE THREAD

**Issue by Ling-jia** [PlexPt/chatgpt-java#22]
![问题](https://user-images.githubusercontent.com/59311273/207380500-daf793a8-0151-4bff-ad77-aa211a821262.png)
请问下调用“Map<String, Object> chatResponse = chatbot.getChatResponse("你好");”
为什么会报错“java.lang.ExceptionInInitializerError”

**Comment by PlexPt** [comment]
Android 先别凑热闹了
