### ISSUE TITLE
functions，function_call已弃用，升级后属性变更：tools， tool_choice

### ISSUE THREAD

**Issue by ticktack** [PlexPt/chatgpt-java#229]
functions，function_call已弃用，升级后属性变更：functions 升级为tools ，function_call 升级为tool_choice

是否可以fix一下这个。

**Comment by PlexPt** [comment]
wip

**Comment by ticktack** [comment]
大佬，什么时候可以更新哈？

**Comment by brotherbear2008** [comment]
同问

**Comment by PlexPt** [comment]
https://github.com/PlexPt/chatgpt-java/commit/3367ae7675001b998af778fafd6ccf1500156c49

**Comment by PlexPt** [comment]
https://github.com/PlexPt/chatgpt-java/releases/tag/4.4.0
