### ISSUE TITLE
ai回复长文本会缺失后半部分信息

### ISSUE THREAD

**Issue by poetryLi** [PlexPt/chatgpt-java#23]
怀疑是网络原因，长文本后半部分内容没返回

**Comment by PlexPt** [comment]
回复 继续



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月14日(周三) 中午11:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PlexPt/chatgpt-java] ai回复长文本会缺失后半部分信息 (Issue #23)




 
怀疑是网络原因，长文本后半部分内容没返回

**Comment by PlexPt** [comment]
#3
