### ISSUE TITLE
超过当前配额 请问作者有准备api key相关的前置知识吗

### ISSUE THREAD

**Issue by RanZiXuan** [PlexPt/chatgpt-java#249]
目前已经准备好chatgpt账号和key
这个配额不知道什么规则 是必须绑卡或者充值吗？

OpenAI  sse连接异常data：{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}
，异常：null

**Comment by PlexPt** [comment]
是必须绑卡充值
