### ISSUE TITLE
报错403

### ISSUE THREAD

**Issue by cqzaiercn** [PlexPt/chatgpt-java#25]
![image](https://user-images.githubusercontent.com/37819946/207530948-4a1c8522-f2ac-40fe-aa84-ba812c54505d.png)

![image](https://user-images.githubusercontent.com/37819946/207530574-412fcb19-715d-4342-81f8-0e4b2a81718d.png)
![image](https://user-images.githubusercontent.com/37819946/207530632-68d7a4ac-b843-4a44-a9af-e4a93328747f.png)
![image](https://user-images.githubusercontent.com/37819946/207530674-cf05d49e-6b81-4200-adc2-45cbbf1f180b.png)
配置了不行

**Comment by cqzaiercn** [comment]
配置了还是不行

**Comment by PlexPt** [comment]
#26

**Comment by PlexPt** [comment]
需要保证IP一致并且过期时间很短，不到2小时

**Comment by hongshunanhai** [comment]
对 我也是session验证的时候一直报403,session_token和userAgent和cfClearance是从浏览器复制的
