### ISSUE TITLE
如何指定模型名称

### ISSUE THREAD

**Issue by Tamrac-web** [PlexPt/chatgpt-java#296]
请问如何指定ChatGPTStream 使用的模型名称

**Comment by Tamrac-web** [comment]
![image](https://github.com/PlexPt/chatgpt-java/assets/93933896/660fe097-f9b5-42cf-bf4b-43d8d90247af)
补充图片

**Comment by PlexPt** [comment]
````
     ConsoleStreamListener listener = new ConsoleStreamListener();
        Message message = Message.of("写一段七言绝句诗，题目是：火锅！");
        ChatCompletion chatCompletion = ChatCompletion.builder()
                .model("gpt-4")
                .messages(Arrays.asList(message))
                .build();
        chatGPTStream.streamChatCompletion(chatCompletion, listener);
```

**Comment by Tamrac-web** [comment]
指定模型名称和指定apihost 无法兼得吗，请问一下有配置文件设置 url 与 key 的地方吗

**Comment by PlexPt** [comment]
请仔细阅读文档，这两个在不同位置设置的

**Comment by Tamrac-web** [comment]
大佬，你仓库remark里太模糊了，可以指一下路吗


zone
________________________________
发件人: plex ***@***.***>
发送时间: Tuesday, July 2, 2024 6:41:58 PM
收件人: PlexPt/chatgpt-java ***@***.***>
抄送: Tamrac ***@***.***>; Author ***@***.***>
主题: Re: [PlexPt/chatgpt-java] 如何指定模型名称 (Issue #296)


请仔细阅读文档，这两个在不同位置设置的

―

**Comment by PlexPt** [comment]
把你截图的代码和我贴出来的结合看即可

**Comment by Tamrac-web** [comment]
谢谢！已解决！！！！！！！！
这里贴一下解决代码以防后面有我这样的小白：
`  SseEmitter sseEmitter = new SseEmitter(-1L);
        SseStreamListener listener = new SseStreamListener(sseEmitter);


     

        ChatGPTStream chatGPTStream = ChatGPTStream.builder()
            .timeout(600)
            .apiHost("http://localhost:49090/")
            .apiKey("key")
            .build()
            .init();

        ChatCompletion chatCompletion = ChatCompletion.builder()
            .model("gpt-4")
            .messages(messages)
            .build();
        
        chatGPTStream
        .streamChatCompletion(chatCompletion,listener);
        listener.setOnComplate(m -> {
            sseEmitter.complete();
        });

        return  sseEmitter;
`
