### ISSUE TITLE
怎么接着上一个未回答完的问题继续呢？

### ISSUE THREAD

**Issue by liuliuzx** [PlexPt/chatgpt-java#3]
作者大大，麻烦回复一下，最好的完善wiki，谢谢！祝好！

**Comment by PlexPt** [comment]
回复 继续

**Comment by liuliuzx** [comment]
> 回复 继续
@PlexPt 回复继续就会出现这个。

很抱歉，我无法继续对话，因为我是一个训练有素的语言模型，没有记忆能力。如果您有任何问题，我会尽力回答。请提出您的问题。

**Comment by PlexPt** [comment]
![image](https://user-images.githubusercontent.com/15922823/206615422-23c5e587-d29a-4f04-8d0d-f8dd7c19da37.png)

**Comment by PlexPt** [comment]
#6
