### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by QiuZiXian** [PlexPt/chatgpt-java#31]
本来是403的，我按#26的方法多试了几次。不报403了。但是没有访问权限
`getChatStream Exception: TYPE html>
getChatStream Exception:  lang="en-US">
getChatStream Exception: ead>
getChatStream Exception:  <title>Access denied</title>
getChatStream Exception:  <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
getChatStream Exception:  <meta name="robots" content="noindex, nofollow" />
getChatStream Exception:  <meta name="viewport" content="width=device-width,initial-scale=1" />
getChatStream Exception:  <link rel="stylesheet" href="/cdn-cgi/styles/errors.css" media="screen" />
getChatStream Exception:  <script>
getChatStream Exception: tion(){if(document.addEventListener&&window.XMLHttpRequest&&JSON&&JSON.stringify){var e=function(a){var c=document.getElementById("error-feedback-survey"),d=document.getElementById("error-feedback-success"),b=new XMLHttpRequest;a={event:"feedback clicked",properties:{errorCode:1020,helpful:a,version:5}};b.open("POST","https://sparrow.cloudflare.com/api/v1/event");b.setRequestHeader("Content-Type","application/json");b.setRequestHeader("Sparrow-Source-Key","c771f0e4b54944bebf4261d44bd79a1e");
getChatStream Exception: d(JSON.stringify(a));c.classList.add("feedback-hidden");d.classList.remove("feedback-hidden")};document.addEventListener("DOMContentLoaded",function(){var a=document.getElementById("error-feedback"),c=document.getElementById("feedback-button-yes"),d=document.getElementById("feedback-button-no");"classList"in a&&(a.classList.remove("feedback-hidden"),c.addEventListener("click",function(){e(!0)}),d.addEventListener("click",function(){e(!1)}))})}})();
getChatStream Exception: ipt>
getChatStream Exception:  <script>
getChatStream Exception:  (function(){function d(c){var b=document.getElementById("copy-label"),a=document.getElementById("cf-details-wrapper-expandable");c.target.checked?a.classList.add("expanded"):(a.classList.remove("expanded"),b.innerText="Click to copy")}if(document.addEventListener){var e=function(){var c=document.getElementById("copy-label");var b=document.getElementById("error-details").textContent;if(navigator.clipboard)navigator.clipboard.writeText(b);else{var a=document.createElement("textarea");a.value=b;a.style.top="0";a.style.left="0";a.style.position="fixed";document.body.appendChild(a);a.focus();a.select();document.execCommand("copy");document.body.removeChild(a)}c.innerText="Copied text to clipboard"};document.addEventListener("DOMContentLoaded",function(){var c=document.getElementById("error-details-checkbox"),b=document.getElementById("click-to-copy-btn");document.getElementById("copy-label").classList.remove("hidden");c.addEventListener("change",d);b.addEventListener("click",e)})}})();
getChatStream Exception:  </script>
getChatStream Exception:  <script defer src="https://performance.radar.cloudflare.com/beacon.js"></script>
getChatStream Exception: head>
getChatStream Exception: ody>
getChatStream Exception: iv class="cf-main-wrapper" role="main">
getChatStream Exception:  <div class="cf-header cf-section">
getChatStream Exception:     <div class="cf-error-title">
getChatStream Exception:        <h1>Access denied</h1>
getChatStream Exception:        <span class="cf-code-label">Error code <span>1020</span></span>
getChatStream Exception:     </div>
getChatStream Exception:     <div class="cf-error-description">
getChatStream Exception:        <p>You do not have access to chat.openai.com.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>
getChatStream Exception:     </div>
getChatStream Exception:  </div>
getChatStream Exception: div>
getChatStream Exception: iv class="cf-details-wrapper">
getChatStream Exception:  <div class="cf-section" role="region">
getChatStream Exception:     <div class="cf-expandable" id="cf-details-wrapper-expandable">
getChatStream Exception:        <label for="error-details-checkbox" title="Error details" class="cf-expandable-btn">
getChatStream Exception:           <p class="cf-dropdown-title">Error details</p>
getChatStream Exception:           <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEUAAAAwMDAxMTEyMjIwMDAxMTF+89HTAAAABXRSTlMAf2CAMKS61bwAAABTSURBVCjPzcq7DcAgFENR5zMATfo06TNCViAS+6+CeFi6gglw4eLqaPVtaQpXnkApaQT/k0dw70EAUhCA1AnABGACMAGYAEwAkCOAydv+I5xaZhXWbQrD80TkkQAAAABJRU5ErkJggg=="
getChatStream Exception:           class="cf-caret-icon" id="caret-icon" alt="Caret icon" />
getChatStream Exception:        </label>
getChatStream Exception:        <input id="error-details-checkbox" class="hidden" type="checkbox">
getChatStream Exception:        <div class="cf-expandable-error-info hidden">
getChatStream Exception:           <p class="cf-error-copy-description">Provide the site owner this information.</p>
getChatStream Exception:           <button class="cf-click-to-copy-btn" id="click-to-copy-btn" title="Click to copy" type="button">
getChatStream Exception: class="cf-error-wrapper" id="error-details"><p class="cf-error-details-endpoint">I got an error when visiting chat.openai.com/backend-api/conversation.</p>
getChatStream Exception: ror code: 1020</p>
getChatStream Exception: y ID: 79209be028d497e7</p>
getChatStream Exception: untry: CN</p>
getChatStream Exception: ta center: sjc05</p>
getChatStream Exception: : 220.250.40.152</p>
getChatStream Exception: mestamp: 2023-01-31 07:07:10 UTC</p>
getChatStream Exception: >
getChatStream Exception:              <p class="cf-copy-label hidden" id="copy-label">Click to copy</p>
getChatStream Exception:           </button>
getChatStream Exception:        </div>
getChatStream Exception:     </div>
getChatStream Exception:  </div>
getChatStream Exception:  <div class="clearfix cf-footer cf-section" role="contentinfo">
getChatStream Exception:  <div class="cf-column">
getChatStream Exception:       <div class="feedback-hidden py-8 text-center" id="error-feedback">
getChatStream Exception: div id="error-feedback-survey" class="footer-line-wrapper">
getChatStream Exception:    Was this page helpful?
getChatStream Exception:    <button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-yes" type="button">Yes</button>
getChatStream Exception:    <button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-no" type="button">No</button>
getChatStream Exception: /div>
getChatStream Exception: div class="feedback-success feedback-hidden" id="error-feedback-success">
getChatStream Exception:    Thank you for your feedback!
getChatStream Exception: /div>
getChatStream Exception: >
getChatStream Exception:  </div>
getChatStream Exception:     <div class="cf-column cf-footer-line-wrapper text-center">
getChatStream Exception:        <p>
getChatStream Exception:           Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=1020_error" target="_blank">Cloudflare <img class="external-link" title="Opens in new tab" src="/cdn-cgi/images/external.png" alt="External link"></a>
getChatStream Exception:        </p>
getChatStream Exception:     </div>
getChatStream Exception:  </div>
getChatStream Exception: div>
getChatStream Exception: pt>(function(){var js = "window['__CF$cv$params']={r:'79209be028d497e7',m:'jgaXBBMueoOydisEO.qS9XaykXP0Ib9PS7yn65yfVyA-1675148830-0-AZmzeISkITeguwqKgEYC4Gn8MGAJfLm3VoiE9NxgqNSeKyaFK3EIYyRVIlv8orKDzZh+NiJfDSuJzGhCsQrtTmmeG7y1yY0Qt2dwKZmC1ItIi3m4QXibYgmQyUkTeDf2uzqoliay5dAH0n6qIInoes0=',s:[0x87d10c320e,0xe7e38ed135],u:'/cdn-cgi/challenge-platform/h/g'};var now=Date.now()/1000,offset=14400,ts=''+(Math.floor(now)-Math.floor(now%offset)),_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible.js?ts='+ts,document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.nonce = '';_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script></body>
getChatStream Exception: l>
null
`

**Comment by PlexPt** [comment]
2月12日更新，配合https://github.com/acheong08/ChatGPT-Proxy 亲测可使用
