### ISSUE TITLE
有没有可能通过apikey实现？

### ISSUE THREAD

**Issue by JerryFoundation** [PlexPt/chatgpt-java#33]
session这玩意很容易掉， 为啥不用apikey来对接？  我觉得可以试试这个方向

**Comment by cantops** [comment]
> session这玩意很容易掉， 为啥不用apikey来对接？ 我觉得可以试试这个方向

官方没有出api，现在大家传的api其实是openai的聊天机器人api，和chatgpt不是一个东西
