### ISSUE TITLE
主分支代码报错

### ISSUE THREAD

**Issue by imyuyu** [PlexPt/chatgpt-java#340]
如图所示

![image](https://github.com/user-attachments/assets/8e9099aa-2b63-497c-9a7b-5066a3bc9bf5)

**Comment by PlexPt** [comment]
lombok插件安装下

**Comment by imyuyu** [comment]
lombok已经安装了，主要原因是因为`Message`对象的`content`类型为`Object`
![image](https://github.com/user-attachments/assets/92431387-f24f-481b-bc2c-4132091ec1b9)
但是`com.knuddels.jtokkit.api.Encoding#countTokens`接收参数为`String`
![image](https://github.com/user-attachments/assets/84116f11-e0e3-4980-b0f4-1fc48315e5ce)
