### ISSUE TITLE
现在问的下文, 没有和上文联系起来了

### ISSUE THREAD

**Issue by codinglz** [PlexPt/chatgpt-java#6]
这一次问的东西, 和上一句没有什么关联了, 使用的是例子上写的方式

**Comment by PlexPt** [comment]
![image](https://user-images.githubusercontent.com/15922823/206615422-23c5e587-d29a-4f04-8d0d-f8dd7c19da37.png)

**Comment by codinglz** [comment]
我使用的是 api 的请求方式
Chatbot chatbot = new Chatbot(sessionData.getSession());
        Map<String, Object> chatResponse = chatbot.getChatResponse(chatData.getMsg());
        System.out.println(chatResponse.get("message"));

**Comment by codinglz** [comment]
我上一句问的是 QQ 是什么?
![image](https://user-images.githubusercontent.com/68374961/206616583-157fe8aa-5587-4cc6-8df2-4056d347c2ba.png)

**Comment by PlexPt** [comment]
一个Chatbot实例为一个Session，会持有对话上下文，可以回复：继续 让机器人接着说。如果需要对话互相隔离，new 多个Chatbot实例即可。

**Comment by codinglz** [comment]
我明白了, 多谢

**Comment by codinglz** [comment]
我每次都 new 了一个新的
