### ISSUE TITLE
没有上下文功能

### ISSUE THREAD

**Issue by joshua-zhr** [PlexPt/chatgpt-java#76]
你好，我发现每次调用好像都没有上下文，都是独立的一次对话，请问能支持一下上下文吗，感谢

**Comment by PlexPt** [comment]
看readme

**Comment by joshua-zhr** [comment]
请问下大佬，ChatContextHolder保存了上下文之后，是要传到ChatCompletion里面吗，但是我看ChatCompletion没有上下文的参数，有点迷惑，望大佬指点
