### ISSUE TITLE
SSE报错：Exception in thread "OkHttp Dispatcher" java.lang.NoSuchFieldError: instance

### ISSUE THREAD

**Issue by reBiocoder** [PlexPt/chatgpt-java#77]
![image](https://user-images.githubusercontent.com/39401819/227168564-158b3159-afaf-498b-a938-5c3d608d2845.png)

**Comment by PlexPt** [comment]
环境信息

**Comment by reBiocoder** [comment]
> 环境信息

您好， windows10，jdk1.8. 本地调测，报上述错误。  启用了代理

**Comment by Searching17** [comment]
> 

请问怎么解决的？

**Comment by retroxz** [comment]
请问应该使用什么版本的okhttp呢
@PlexPt

**Comment by PlexPt** [comment]
3.14.9

**Comment by PlexPt** [comment]
> 请问应该使用什么版本的okhttp呢 @PlexPt

3.14.9
