### ISSUE TITLE
开启上下文后，就聊了几句他就说token太长了

### ISSUE THREAD

**Issue by smokingrain** [PlexPt/chatgpt-java#79]
请求异常：{
  "error": {
    "message": "This model's maximum context length is 4097 tokens. However, you requested 4103 tokens (103 in the messages, 4000 in the completion). Please reduce the length of the messages or completion.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
主要是这里，(103 in the messages, 4000 in the completion)，completion花了4000个token

**Comment by inseru** [comment]
你如何开启的上下文？

**Comment by smokingrain** [comment]
@inseru 通过ChatContextHolder带入每一次提问。问题解决了，设置ChatCompletion.maxTokens(4000)会导致响应有可能带回大量token，改成设置成300即可

**Comment by PlexPt** [comment]
https://github.com/PlexPt/chatgpt-online-springboot
