### ISSUE TITLE
请求兼容model text-davinci-003

### ISSUE THREAD

**Issue by IllTamer** [PlexPt/chatgpt-java#8]
或想请您告知为何model text-davinci-003不可用，我更改参数后返回的数据显示
```json
{"detail":"Engine text-davinci-003 not recognized"}
```

**Comment by PlexPt** [comment]
请更详细地描述

**Comment by IllTamer** [comment]
我从官网得知最新版的模型应该是 `text-davinci-003`

![image](https://user-images.githubusercontent.com/78360471/206637293-361bc235-b65f-4784-b4bd-d390d609c77a.png)

但我查看当前项目源码，发现使用的模型为 `text-davinci-002-render`

![image](https://user-images.githubusercontent.com/78360471/206637470-cd36506e-acc0-444b-bcfc-fb7f3aef6193.png)

遂想更改模型版本，尝试调用 `text-davinci-003` 处理对话，便重写了 `getChatResponse(String prompt, String output)` 方法并仅修改了 `data.put("model", "text-davinci-003");` 一句。而后在调试时发现 `getChatText(Map<String, Object> data)` 方法中存在报错，原因是如下代码解析 `part` 变量出错：
```java
                String part = s.substring(5);
                JSONObject lineData = JSON.parseObject(part);
```
我将变量 `s` 进行输出查看发现当model设置为 text-davinci-003 后，调用api返回的信息为
```
{"detail":"Engine text-davinci-003 not recognized"}
```

**Comment by PlexPt** [comment]
用这个https://github.com/TheoKanning/openai-java

**Comment by IllTamer** [comment]
感谢您的帮助！我是第一次接触openai，能否烦请您再解释下003模型不可用的原因，是该项目调用的api暂未支持到003版本吗><
