### ISSUE TITLE
请教下，封号风险是指封什么号？ 是chatGPT账号么， 它本身不是支持api调用么？

### ISSUE THREAD

**Issue by wt1024** [PlexPt/chatgpt-java#89]
这个“封号风险”是指chatGPT账号么？ 它本身就支持api调用并且收费为什么还有可能封号？
<img width="853" alt="image" src="https://user-images.githubusercontent.com/10046468/228442336-51db4d00-cc1f-4247-9677-ddb5c97cb59d.png">

**Comment by pansx** [comment]
据我所知有两方面
一方面,这个包是支持白嫖的,也就是直接逆向官方界面不使用apikey,这种方式会导致封号
另一方面,plus会员也有tos,你的用户用你的key来问涩擎暴力反国外政治正确的问题时会被封号

**Comment by wt1024** [comment]
> 据我所知有两方面 一方面,这个包是支持白嫖的,也就是直接逆向官方界面不使用apikey,这种方式会导致封号 另一方面,plus会员也有tos,你的用户用你的key来问涩擎暴力反国外政治正确的问题时会被封号

感谢感谢
