### ISSUE TITLE
illegal input， offset 1, char a

### ISSUE THREAD

**Issue by xjx1213318058** [PlexPt/chatgpt-java#9]
![image](https://user-images.githubusercontent.com/96099210/206680342-a1499a7e-0b79-4e4c-a20d-d3df39c2b73e.png)
我不是很理解,为什么会报这个错误?

**Comment by PlexPt** [comment]
token过期了

**Comment by xjx1213318058** [comment]
可是我已经重新抓token了,而且我还加了账号和密码,同样还是报这个错误

**Comment by xjx1213318058** [comment]
我已经重新抓token,还是报这个错误,然后我把token干掉,换成了账号和密码也还是不行

**Comment by xjx1213318058** [comment]
![image](https://user-images.githubusercontent.com/96099210/206685918-5fac14d3-89db-4460-aab8-10546d437bd7.png)
就像这样子,账号和密码,它自己获取的token,但是还是会报错

**Comment by PlexPt** [comment]
不要加账号密码



---Original---
From: ***@***.***&gt;
Date: Fri, Dec 9, 2022 18:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PlexPt/chatgpt-java] illegal input， offset 1, char a (Issue #9)




 
可是我已经重新抓token了,而且我还加了账号和密码,同样还是报这个错误
