### ISSUE TITLE
ChatContextHolder 上下文类改怎么使用？如何让chatGPT感知上下文呢？

### ISSUE THREAD

**Issue by inseru** [PlexPt/chatgpt-java#90]

**Comment by jiaw3i** [comment]
用ChatContextHolder保存历史对话，在每一次请求ChatGPT的时候带上历史对话

**Comment by 263055** [comment]
> 用ChatContextHolder保存历史对话，在每一次请求ChatGPT的时候带上历史对话

这个类"ChatContextHolder"是利用了Map存放了历史对话，我有两个疑问点：
首先用map存放到内存中我认为有些不太合适，如果对话内容过多会不会导致内存过大
第二点：这个似乎不支持多用户，这段代码并没有设置多线程去保存不同用户的对话

**Comment by jiaw3i** [comment]
> > 用ChatContextHolder保存历史对话，在每一次请求ChatGPT的时候带上历史对话
> 
> 这个类"ChatContextHolder"是利用了Map存放了历史对话，我有两个疑问点： 首先用map存放到内存中我认为有些不太合适，如果对话内容过多会不会导致内存过大 第二点：这个似乎不支持多用户，这段代码并没有设置多线程去保存不同用户的对话

作者可能只是写个示例而已。具体怎么存储历史对话，完全可以根据自己需求定制化

**Comment by PlexPt** [comment]
https://github.com/PlexPt/chatgpt-online-springboot
