### ISSUE TITLE
在使用Stream流式调用的时候，文本里面的 '\n' 等字符是不是被去掉了

### ISSUE THREAD

**Issue by guanqing123** [PlexPt/chatgpt-java#96]

**Comment by EasonKobe** [comment]
但是前端输出英文的时候是没有空格的，这个要怎么处理呢

**Comment by Mrcxl** [comment]
自己写一个监听器 SseStreamListener 继承AbstractStreamListener 重写 onEvent 方法   
    @Override
    public void onEvent(EventSource eventSource, String id, String type, String data) {

        if (data.equals("[DONE]")) {
//发送结束标记
            sseEmitter.send("[DONE]");
            this.onComplate.accept(this.lastMessage);
        } else {
            this.onMsg(data);
        }
    }

**Comment by EasonKobe** [comment]
> 自己写一个监听器 SseStreamListener 继承AbstractStreamListener 重写 onEvent 方法
> 
> ```java
>     @Override
>     public void onEvent(EventSource eventSource, String id, String type, String data) {
> 
>         if (data.equals("[DONE]")) {
> //发送结束标记
>             sseEmitter.send("[DONE]");
>             this.onComplate.accept(this.lastMessage);
>         } else {
>             this.onMsg(data);
>         }
>     }
> ```

这个跟没有空格没关系吧

**Comment by Mrcxl** [comment]
我不知道你的，反正我是这样解决的,我已经解决！

**Comment by EasonKobe** [comment]
> 我不知道你的，反正我是这样解决的,我已经解决！

解决英文没有空格的问题吗

**Comment by guanqing123** [comment]
public class YSseStreamListener extends AbstractStreamListener {

    final SseEmitter sseEmitter;

    @Override
    public void onEvent(EventSource eventSource, String id, String type, String data) {
        if (data.equals("[DONE]")) {
            onMsg(data);
            onComplate.accept(lastMessage);
            return;
        }
     。。。
    }

    @Override
    public void onMsg(String message) {
        String data = message.replaceAll(" ", "&#32;").replaceAll("\\n", "&#92n");
        SseHelper.send(sseEmitter, data);
    }
}

发之前替换一个，空格和 \n 可以保留。前端再自己替换一下

**Comment by 263055** [comment]
> 

public class YSseStreamListener extends AbstractStreamListener {
    final SseEmitter sseEmitter;
    @Override
    public void onEvent(EventSource eventSource, String id, String type, String data) {
        if (data.equals("[DONE]")) {
            onMsg(data);
            onComplate.accept(lastMessage);
            return;
        }
    }
    @Override
    public void onMsg(String message) {
        String data = message.replaceAll(" ", "&#32;").replaceAll("\\n", "&#92n");
        SseHelper.send(sseEmitter, data);
    }
    @Override
    public void onError(Throwable throwable, String s) {
    }
}
你好，你的这段代码，它提示我"变量 'sseEmitter' 可能尚未初始化"
当我加入@Configuration的时候它依然提示我"变量 'sseEmitter' 可能尚未初始化"
这个代码应该怎么修改？还是在源代码中进行修改，大佬能不能给出完整的代码

**Comment by 263055** [comment]
> 没有

我的前端代码如下：
···
  source = new EventSource(`http://localhost:8080/comment/addCommentDetail/?${params}`, {headers})
  source.onmessage = (event) => {
    const commentText = event.data;
    const commentElement = document.createElement('div');
    commentElement.innerHTML = commentText; // 使用innerHTML而不是textContent来设置HTML内容
    newCommentArray[1] += commentElement.innerHTML;
  };
  ···
  后端代码直接返回了sseEmitter，然后将newCommentArray[1] 展示到页面上
  {{newCommentArray[1] }}
  此时的结果是
  ···
   undefined可以使用以下代码实现：```pythonprint("Hello,World!")```运行这段代码，屏幕上将输出"Hello,World!"。
   ···
   而预期的结果是
   ···
    可以使用以下代码实现：

```python
print("Hello, World!")
```

运行这段代码，屏幕上将输出"Hello, World!"。
   ···

**Comment by PlexPt** [comment]
https://github.com/PlexPt/chatgpt-online-springboot
