### ISSUE TITLE
spring SseEmitter没有返回任何数据

### ISSUE THREAD

**Issue by twelvet-s** [PlexPt/chatgpt-java#98]
按照文档的例子写法，SseEmitter没有给输出任何数据
listener.setOnComplate(msg -> {
            // 回答完成，可以做一些事情
            log.info("======ChatGPT=======：{}", msg);
        });
这段代码可以看到有回答的，就是SseEmitter没有给前端返回数据，是为什么呢，麻烦了

**Comment by twelvet-s** [comment]
它只支持GET请求建立链接，但是改了GET一样接受不到请求

**Comment by twelvet-s** [comment]
我使用的postman测试数据，因为结束后，没有正确关闭流导致的。我提交个pr修正他

**Comment by twelvet-s** [comment]
我找到了问题，是我拦截器问题，但还是希望能够优雅关闭他sseEmitter.complete();

**Comment by jiaw3i** [comment]
> 它只支持GET请求建立链接，但是改了GET一样接受不到请求

你可以使用fetch-event-source

**Comment by twelvet-s** [comment]
> > 它只支持GET请求建立链接，但是改了GET一样接受不到请求
> 
> 你可以使用fetch-event-source

那他应该也是可以通过这种方式去发送body参数的吧，我不想后端放上下数据，谢谢啦

**Comment by PlexPt** [comment]
贴出前端代码
